name: completiontimes
channels:
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - numpy=1.26.4
  - scipy

  - cudatoolkit=12.0
  - cuml
  - cupy
  - ocl-icd-system

  - lightgbm
  - xgboost
  - pmdarima
  - statsmodels
  - mlxtend
  - shap
  - tslearn
  - kneed

  - aiohttp
  - motor
  - backoff

  - pyyaml
  - python-dotenv
  - optuna
  - tqdm

  - matplotlib
  - seaborn

  - pip
  - pip:
      - prophet
      - holidays==0.70
